### ISSUE TITLE
تایید هویت

### ISSUE THREAD

**Issue by behrad-ahmadpour** [vahidbk/AutoRobotOnlinePlusMofidTrader#1]
سلام خسته نباشید

سوالی که داشتم ازتون در خصوص تایید هویت است.....وقتی لاگین میکنید با حرکت در صفحات مختلف از کجا به سایت میگید که هویت شما چیست؟ آیا در ابتدا csrf توکن از سایت میگیرید؟

**Comment by jafaryehsan** [comment]
سلام 
من به یک مشکل برخوردم و اون اینکه وقتی برنامه اجرا میشه صفحه لاگین لود میشه و سپس قبل از اینکه من بتونم اطلاعاتم رو وارد کنم صفحه بسته میشه...
میتونین کمکم کنین لطفا

**Comment by vahidbk** [comment]
سلام
سئوالتون مفهوم نیست . سیستم عاملتون چی است؟ چه کارهایی تا حالا انجام دادید
و چقدر پایتون کار کردید؟ این برنامه با سلنیوم کار می کنه و ریکوست پایتون.

‫‪jafaryehsan‬‏ <‪notifications@github.com‬‏> در تاریخ یکشنبه ۲۰ دسامبر
۲۰۲۰ ساعت ۲۳:۳۲ نوشت:‬
